[phases.setup]
nixpkgs = ["nodejs", "python3", "gcc"]

[phases.build]
cmds = [
  "pip install -r requirements.txt",
  "cd theme/static_src",
  "npm install",
  "cd ../..",
  "npm run build",
  "python manage.py collectstatic --noinput",
  "python manage.py migrate"
]

[start]
cmd = "python manage.py runserver 0.0.0.0:$PORT"