[build]
nixpacksVersion = "1.19.0"
providers = ["python", "node"]

[phases.setup]
nixpkgs = ["python311Full", "gcc", "openssl"]

[phases.install]
cmds = [
  "which python3",
  "python3 --version",
  "which pip",
  "pip --version",
  "pip install -r requirements.txt",
  "cd theme/static_src && npm install"
]


[phases.build]
cmds = [
  "cd theme/static_src && npm run build",
  "python manage.py collectstatic --noinput",
  "python manage.py migrate"
]

[start]
cmd = "gunicorn Kreativ.wsgi:application --bind 0.0.0.0:$PORT"