[build]
nixpacksVersion = "1.19.0"
providers = ["python", "node"]

[phases.setup]
nixpkgs = ["gcc", "openssl", "pkgs.python312.withPackages (ps: with ps; [ pip setuptools wheel ])"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "cd theme/static_src && npm install"
]


[phases.build]
cmds = [
  "cd theme/static_src && npm run build",
  "python manage.py collectstatic --noinput",
  "python manage.py migrate"
]

[start]
cmd = "gunicorn Kreativ.wsgi:application --bind 0.0.0.0:$PORT"