# Generated by Django 4.2.6 on 2025-01-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre')),
                ('image', models.ImageField(blank=True, max_length=128, null=True, upload_to='assets/', verbose_name="Image de l'article")),
            ],
        ),
    ]
