# Generated by Django 4.2.6 on 2025-01-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SousContenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souscontenu',
            name='sous_titre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='sous titre'),
        ),
    ]
